[package]
name = "cosmic-store"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.10"
lazy_static = "1"
lexical-sort = "0.3"
log = "0.4"
paste = "1"
rayon = "1"
regex = "1"
serde = { version = "1", features = ["serde_derive"] }
tokio = { version = "1" }
# Internationalization
i18n-embed = { version = "0.13", features = ["fluent-system", "desktop-requester"] }
i18n-embed-fl = "0.6"
rust-embed = "6"
# appstream (should this be a feature?)
appstream = { version = "0.2", path = "appstream" }
flate2 = "1"
sys-locale = "0.3"
serde_yaml = "0.9"
# flatpak feature
libflatpak = { version = "0.4", optional = true }
# packagekit feature
packagekit-zbus = { version = "0.1", optional = true }

[dependencies.libcosmic]
git = "https://github.com/pop-os/libcosmic.git"
default-features = false
features = ["tokio", "winit"]
#path = "../libcosmic"

[features]
default = ["flatpak", "packagekit", "wgpu"]
flatpak = ["dep:libflatpak"]
packagekit = ["dep:packagekit-zbus"]
wgpu = ["libcosmic/wgpu"]

[patch.crates-io]
smithay-client-toolkit = { git = "https://github.com/pop-os/client-toolkit", branch = "wayland-resize" }

[profile.release-with-debug]
inherits = "release"
debug = true

[target.'cfg(unix)'.dependencies]
fork = "0.1"
